select
    s.order_id,
    s.quantity,
    s.unit_price,
    s.discount,
    s.status_id,
    s.date_allocated,
    s.purchase_order_id,
    s.inventory_id,
    s.order_date,
    s.shipped_date,
    s.paid_date,
    s.customer_id,
    c.company                   as customer_company,
    c.last_name                 as customer_last_name,
    c.first_name                as customer_first_name,
    c.email_address             as customer_email_address,
    c.job_title                 as customer_job_title,
    c.business_phone            as customer_business_phone,
    c.home_phone                as customer_home_phone,
    c.mobile_phone              as customer_mobile_phone,
    c.fax_number                as customer_fax_number,
    c.address                   as customer_address,
    c.city                      as customer_city,
    c.state_province            as customer_state_province,
    c.zip_postal_code           as customer_zip_postal_code,
    c.country_region            as customer_country_region,
    c.web_page                  as customer_web_page,
    c.notes                     as customer_notes,
    c.attachments               as customer_attachments,
    s.employee_id,
    e.company                   as employee_company,
    e.last_name                 as employee_last_name,
    e.first_name                as employee_first_name,
    e.email_address             as employee_email_address,
    e.job_title                 as employee_job_title,
    e.business_phone            as employee_business_phone,
    e.home_phone                as employee_home_phone,
    e.mobile_phone              as employee_mobile_phone,
    e.fax_number                as employee_fax_number,
    e.address                   as employee_address,
    e.city                      as employee_city,
    e.state_province            as employee_state_province,
    e.zip_postal_code           as employee_zip_postal_code,
    e.country_region            as employee_country_region,
    e.web_page                  as employee_web_page,
    e.notes                     as employee_notes,
    e.attachments               as employee_attachments,
    s.product_id,
    p.product_code              as product_product_code,
    p.product_name              as product_product_name,
    p.description               as product_description,
    p.supplier_company          as product_supplier_company,
    p.standard_cost             as product_standard_cost,
    p.list_price                as product_list_price,
    p.reorder_level             as product_reorder_level,
    p.target_level              as product_target_level,
    p.quantity_per_unit         as product_quantity_per_unit,
    p.discontinued              as product_discontinued,
    p.minimum_reorder_quantity  as product_minimum_reorder_quantity,
    p.category                  as product_category,
    p.attachments               as product_attachments,
    s.shipper_id
from {{ref('fact_sales')}} s
left join {{ref('dim_customer')}} c
on c.customer_id = s.customer_id
left join {{ref('dim_employee')}} e
on e.employee_id = s.employee_id
left join {{ref('dim_product')}} p
on p.product_id = s.product_id